export const skills = {
  frontend: [
    "React",
    "TypeScript",
    "Webpack",
    "Vite",
    "Module Federation",
    "Next.js",
    "Redux",
    "RTK",
    "RTK Query",
    "MobX",
    "HTML5",
    "CSS3",
    "SCSS",
    "Tailwind CSS",
    "Styled-Components",
  ],
  backend: [
    "Node.js",
    "Express",
    "PostgreSQL",
    "Sequelize ORM",
    "Firebase",
    "Socket.io",
  ],
  tools: ["Git", "GitLab", "CI/CD", "Docker", "Figma"],
  other: ["GraphQL", "REST APIs", "Jest", "Agile"],
};
